context:
  version: VERSION_PLACEHOLDER

package:
  name: r-qqtlr
  version: ${{ version }}

source:
  path: qqtlr-${{ version }}.tar.gz
  sha256: SHA256SUM_PLACEHOLDER

build:
  number: BUILD_PLACEHOLDER
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/
  script: R CMD INSTALL --build .

requirements:
  host:
    - bioconductor-qvalue
    - r-base
    - r-bigsnpr
    - r-bigstatsr
    - r-dplyr
    - r-pecotmr
    - r-quadprog
    - r-quantreg
    - r-readr
    - r-rfast
    - r-susier
    - r-tidyr
    - r-vroom
    - r-xicor
  run:
    - bioconductor-qvalue
    - r-base
    - r-bigsnpr
    - r-bigstatsr
    - r-dplyr
    - r-pecotmr
    - r-quadprog
    - r-quantreg
    - r-readr
    - r-rfast
    - r-susier
    - r-tidyr
    - r-vroom
    - r-xicor

tests:
  - script:
      - R -e "library('qQTLR')"

about:
  license: MIT
  license_file: LICENSE
  summary: qQTLR implements quantile QTL (qQTL) analysis and quantile-based transcriptome-wide association study (qTWAS) pipelines for distributional genetic effects on molecular phenotypes.
  homepage: https://github.com/StatFunGen/qQTLR

extra:
  recipe-maintainers:
    - danielnachun
